### ISSUE TITLE
Clojurephant and Gradle fail to resolve and compile transitive dependencies when using composite builds.

### ISSUE THREAD

**Issue by jzwolak** [clojurephant/clojurephant#191]
## Expected Behavior

I expect Gradle composite builds to capture transitive dependencies for Clojure code, transitive dependencies for Clojure to Java code, and to compile all necessary Clojure code just as it does when the composite build is not used and instead the jar is downloaded from Clojars. I expect this to work even if the artifact does not yet exist on Clojars.

## Current Behavior

Gradle cannot find the transitive dependencies or compile those Clojure based transitive dependencies. Of course, this works if all the dependencies are Java based dependencies with class files inside. The problem occurs when Clojure code and Clojurephant are being used. Using AOT can partially help, but still, the project will not succeed. The example project I have attached has both Clojure and Java transitive dependencies. Using AOT I can get one level of transitive dependencies. If I specify AOT for all the dependencies, that works... except for the Java dependencies. When the Clojure code depends on Java code, the Java dependencies don't make it to Project A from Project B. See the example project and the README.md.

## Context

I'm using composite builds to avoid publishing my projects to maven while debugging. Some of my projects are Clojure code with Gradle as the build tool. It would be exceptionally useful if I could debug a dependent project and use Gradle's composite build feature to automatically and seamlessly include the changes before publishing those changes. Especially given the changes may be debugging code and not even potential fixes.

## Steps to reproduce

I have attached two sample projects that work together using Gradle's composite build feature. Execute `./gradlew run` from `project-a` and observe the build fails. I would expect the build to succeed and output - among other things - "hi from b".

## Environment

- Build scan URL: https://gradle.com/s/cx7zjtxz4n4ny
- clojurephant version: 0.6.0
- Gradle 7.3.3
- java version "11.0.6" 2020-01-14 LTS
- macOS 12.5

[clojurephant-composite-builds.zip](https://github.com/clojurephant/clojurephant/files/9277704/clojurephant-composite-builds.zip)

**Comment by ajoberstar** [comment]
This is mostly a general Gradle issue, but one we should document better on our side.

Gradle has a pretty involved set of views on the classpath that are used in different contexts:

- `compileClasspath` (a resolvable configuration)
  - Description: What the _current project_ needs to compile itself
  - Includes dependencies from `apiCompileOnly`, `api`, `compileOnly`, and `implementation`
  - Transitively includes (for lack of a better term) _exported_ compile dependencies (e.g. those that would be in the `compile` scope of a Maven POM)
- `runtimeClasspath` (a resolvable configuration)
  - Description: What the _current project_ needs to run itself
  - Includes dependencies from `api`, `implementation`, and `runtimeOnly`
  - Transitively includes _exported_ runtime dependencies (e.g. those that would be in the `runtime` scope of a Maven POM)
As with Java's compile tasks in Gradle, the `compileClojure` and `checkClojure` tasks use the source set's `compileClasspath`. However, Gradle doesn't just distinguish between compile and runtime, they also distinguish between dependencies that should be "exported" as compile dependencies and "exported" as runtime dependencies.
- `apiElements` (an outgoing configuration)
  -  Description: What _another project_ would need to compile against the current project
  - Includes the JAR (with compiled classes and/or Clojure sources)
    - By default _no dependencies_ are exported via this configuration
    - With `java-library` enabled the `api` and `apiCompileOnly` dependencies are exported
  - If you have a project dependency on a project, this is the configuration that's pulled in at compile time
- `runtimeElements` (an outgoing configuration)
  -  Description: What _another project_ would need to run with the current project
  - Includes the JAR (with compiled classes and/or Clojure sources)
    - Exports all `runtimeClasspath` dependencies
  - If you have a project dependency on a project, this is the configuration that's pulled in at runtime

So in this case, because your `project-b` dependencies are in the `implementation` bucket they won't be exported via `apiElements`. And unless you use the `java-library` plugin instead of `application` you won't even have the `api` configuration that could export them.

I think the main two options are either:

1. If appropriate, use the `java-library` plugin instead of `application` and declare your `project-b` dependencies (needed for compile) in the `api` configuration
2. Configure `apiElements` to extend `implementation` in `project-b`
   ```groovy
   configurations.apiElements {
     extendsFrom(configurations.implementation)
   }
   ```

**Comment by ajoberstar** [comment]
Here's some additional background in Gradle's docs:

[Java Library Plugin](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph)
[Maven POM dependency mapping to Gradle variants](https://docs.gradle.org/current/userguide/variant_model.html#sub:maven-mapping-to-variants)

**Comment by jzwolak** [comment]
Thank you, Andrew.

I did not try solution 1 but I did try solution 2 and it worked.

The only reason I used the `application` plugin for project-b was so that I could run it and test it to be sure things were working and the problem wasn't actually in project-b. Originally, I did not include that plugin. The `application` plugin is not included in my production code that this example is drawn from.

This solution will work for me. Thank you so much for spending time on this!

**Comment by ajoberstar** [comment]
Glad to hear that worked for you! For future reference, I added a new doc to try to explain this.
 https://clojurephant.dev/clojurephant/main/explanation/dependencies.html

**Comment by jzwolak** [comment]
Thanks Andrew! The documentation you wrote looks great! I suggestion one addition somewhere. It would be good to mention Gradle's "composite build" feature anywhere in the documentation you wrote. I don't think it's necessary to go into detail, but have the words there will make the document turn up in a Google search (as this issue will already, of course). It could be as simple as in the "Consumable Configurations" section adding a sentence to the first paragraph stating "Downstream consumers can be from a composite build, parent project, ..." and whatever else, I don't know Gradle well enough to know what all should be listed there. But having a short list of examples of downstream consumers would have helped me a lot.

**Comment by ajoberstar** [comment]
@jzwolak Good suggestion, I've added a note about this to the doc
